const types = {
  // App types
  REGISTER_ACCOUNT: 'REGISTER_ACCOUNT',
  CREATE_ACCOUNT: 'CREATE_ACCOUNT',
  LOGIN_USER: 'LOGIN_USER',
  DISPLAY_LOGIN: 'DISPLAY_LOGIN',
  ADMIN_AREA: 'ADMIN_AREA',
  INGAME_PAGE: 'INGAME_PAGE',
  LOG_OUT: 'LOG_OUT',

  // Admin types
  CREATE_HEROTEMPLATE: 'CREATE_HEROTEMPLATE',
  GET_ALL_HEROTEMPLATE: 'GET_ALL_HEROTEMPLATE',
  DELETE_HEROTEMPLATE: 'DELETE_HEROTEMPLATE',
  CREATE_SPELL: 'CREATE_SPELL',
  GET_ALL_SPELLS: 'GET_ALL_SPELLS',
  DELETE_SPELL: 'DELETE_SPELL',
  UPDATE_SPELL: 'UPDATE_SPELL',
  CREATE_ITEM_TYPE: 'CREATE_ITEM_TYPE',
  GET_ALL_ITEM_TYPES: 'GET_ALL_ITEM_TYPES',
  DELETE_ITEM_TYPE: 'DELETE_ITEM_TYPE',
}

export default types
