const types = {
  // App types
  REGISTER_ACCOUNT: 'REGISTER_ACCOUNT',
  CREATE_ACCOUNT: 'CREATE_ACCOUNT',
  LOGIN_USER: 'LOGIN_USER',
  VERIFY_JWT: 'VERIFY_JWT',
  DISPLAY_LOGIN: 'DISPLAY_LOGIN',
  ADMIN_AREA: 'ADMIN_AREA',
  INGAME_PAGE: 'INGAME_PAGE',
  LOG_OUT: 'LOG_OUT',

  // Admin types

  // Herotemplate
  CREATE_HEROTEMPLATE: 'CREATE_HEROTEMPLATE',
  GET_ALL_HEROTEMPLATE: 'GET_ALL_HEROTEMPLATE',
  DELETE_HEROTEMPLATE: 'DELETE_HEROTEMPLATE',
  UPDATE_HEROTEMPLATE: 'UPDATE_HEROTEMPLATE',

  // Spell
  CREATE_SPELL: 'CREATE_SPELL',
  GET_ALL_SPELLS: 'GET_ALL_SPELLS',
  DELETE_SPELL: 'DELETE_SPELL',
  UPDATE_SPELL: 'UPDATE_SPELL',

  // Item type
  CREATE_ITEM_TYPE: 'CREATE_ITEM_TYPE',
  GET_ALL_ITEM_TYPES: 'GET_ALL_ITEM_TYPES',
  DELETE_ITEM_TYPE: 'DELETE_ITEM_TYPE',

  // Item prefix
  CREATE_ITEM_PREFIX: 'CREATE_ITEM_PREFIX',
  GET_ALL_ITEM_PREFIXS: 'GET_ALL_ITEM_PREFIXS',
  DELETE_ITEM_PREFIX: 'DELETE_ITEM_PREFIX',

  // Item suffix
  CREATE_ITEM_SUFFIX: 'CREATE_ITEM_SUFFIX',
  GET_ALL_ITEM_SUFFIXS: 'GET_ALL_ITEM_SUFFIXS',
  DELETE_ITEM_SUFFIX: 'DELETE_ITEM_SUFFIX',

  // Item rarity
  CREATE_ITEM_RARITY: 'CREATE_ITEM_RARITY',
  GET_ALL_ITEM_RARITYS: 'GET_ALL_ITEM_RARITYS',
  DELETE_ITEM_RARITY: 'DELETE_ITEM_RARITY',

  // Enemies
  CREATE_ENEMIE: 'CREATE_ENEMIE',
  GET_ALL_ENEMIES: 'GET_ALL_ENEMIES',
  UPDATE_ENEMIE: 'UPDATE_ENEMIE',
  DELETE_ENEMIE: 'DELETE_ENEMIE',
}

export default types
